language: php
sudo: false
php:
  - "5.4"
before_script:
  - echo "short_open_tag = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install
services:
script: "./vendor/bin/phpunit"
notificaitons:
  irc: "irc.freenode.org#kwf"

# caching doesn't work for free travis atm, but one day it probably will
cache:
  directories:
    - $HOME/.composer/cache
